# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - run: go build -v ./...
    - run: go test -v ./...      

  changelog:    
    runs-on: ubuntu-latest
    needs: build
    permissions:
      actions: write
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Generate CHANGELOG.md
        uses: TriPSs/conventional-changelog-action@v3
        with:
          release-count: '10'
          git-message: 'chore(ci): changelog update'
