# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...      

  changelog:    
    runs-on: ubuntu-latest
    needs: build
    permissions:
      actions: write
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Generate CHANGELOG.md
        uses: TriPSs/conventional-changelog-action@v3
        with:
          release-count: '10'
          git-message: 'chore(ci): changelog update'
